title: Julia Anti-Patterns
description: >-
  Learning what to do in Julia by learning what not to do in Julia. A collection
  of common pitfalls to avoid when using the Julia language, along with
  suggested solutions.
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
